// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jjvtxiaalguxcgvtocqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpqdnR4aWFhbGd1eGNndnRvY3FyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU5NDY1NjgsImV4cCI6MjA1MTUyMjU2OH0.VZ7fz5FgSpIoSoa7_hE0RVhKsLOxekVb5-ZdIhoapXI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);